const styles = {
  box: {
    maxWidth: "360px",
    borderRadius: "8px",
    border: "1px solid #dee2e6",
    overflow: "hidden",
  },
  figure: { margin: "0" },
  img: { display: "block", width: "100%", height: "189px", objectFit: "cover" },
  title: {
    display: "flex",
    flexFlow: "row nowrap",
    alignItems: "center",
    gap: "16px",
    margin: "16px",
  },
  titleText: { flex: "1", margin: "0", fontSize: "20px", fontFamily: "Jua" },
  titleCategory: {
    padding: "0 10px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "700",
    lineHeight: "22px",
    backgroundColor: "#e7f5ff",
    color: "#228be6",
  },
  summary: { margin: "16px", lineHeight: "1.666", color: "#000000cc" },
  footer: {
    display: "flex",
    flexFlow: "row",
    gap: "16px",
    alignItems: "stretch",
    justifyContent: "flex-end",
    padding: "8px 16px 16px 16px",
    borderTop: "1px solid #dee2e6",
  },
  btnDetails: {
    flex: 1,
    display: "inline-flex",
    flexFlow: "row",
    alignItems: "center",
    justifyContent: "center",
    height: "36px",
    padding: "0px 16px",
    border: "1px solid transparent",
    borderRadius: "8px",
    backgroundColor: "#228be6",
    color: "#fff",
    fontSize: "14px",
    fontWeight: "700",
    textDecoration: "none",
  },
  btnFavorite: {
    flex: "0 0 auto",
    display: "inline-flex",
    flexFlow: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
    padding: "0px",
    border: "1px solid #ced4da",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    color: "#fa5252",
    fontSize: "18px",
    fontWeight: "700",
    textDecoration: "none",
    cursor: "pointer",
  },
};

export default styles;
